spring.application.name=event-ticketing-system
server.port=8080

# DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing_db
# Replace and enter your DB's username and password (DO NOT COMMIT YOUR PW TO GITHUB!)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
